source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.2'
use_frameworks!

target 'MyMiniMap' do
   source 'https://github.com/CocoaPods/Specs.git'
     pod 'GoogleMaps'
     pod 'GooglePlaces'
#     pod 'Alamofire', '~> 5.0.0-beta.5'
     pod 'Alamofire', '~> 4.7.3'
     pod 'BSImagePicker', '~> 2.8'
     pod 'SDWebImage', '~> 5.0'
end
